#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Indexer for Vietnamese legal chunks.

Input:
- JSON generated by legal_chunker.py (default: data/metadata/processed_data.json)

Outputs:
- BM25 index (pickle)
- Qdrant vector collection
"""

from __future__ import annotations

import argparse
import json
import pickle
import re
import sys
from pathlib import Path
from pyvi import ViTokenizer
from typing import Any, Dict, List, Sequence


def safe_console_print(message: str) -> None:
    encoding = getattr(sys.stdout, "encoding", None) or "utf-8"
    safe_message = message.encode(encoding, errors="replace").decode(encoding, errors="replace")
    print(safe_message)


def normalize_whitespace(text: str) -> str:
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


# def simple_tokenize(text: str) -> List[str]:
#     # Unicode-aware tokenization that works reasonably for Vietnamese.
#     return re.findall(r"\w+", text.lower(), flags=re.UNICODE)


def ensure_parent(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def _normalize_chunk_record(raw: Dict[str, Any]) -> Dict[str, Any] | None:
    """
    Accept 2 schemas:
    1) {"content": "...", "metadata": {...}}
    2) legal_chunker schema with "text" and flat metadata fields
    """
    if "content" in raw:
        content = normalize_whitespace(str(raw.get("content", "")))
        metadata = raw.get("metadata", {})
        if not isinstance(metadata, dict):
            metadata = {"raw_metadata": metadata}
    elif "text" in raw:
        content = normalize_whitespace(str(raw.get("text", "")))
        metadata = {k: v for k, v in raw.items() if k != "text"}
    else:
        return None

    if not content:
        return None

    metadata = dict(metadata)
    metadata.setdefault("char_len", len(content))

    return {
        "content": content,
        "metadata": metadata,
    }


def load_chunks(input_file: Path, limit: int | None = None) -> List[Dict[str, Any]]:
    if not input_file.exists():
        raise FileNotFoundError(f"Input JSON not found: {input_file.as_posix()}")

    payload = json.loads(input_file.read_text(encoding="utf-8"))
    if not isinstance(payload, list):
        raise ValueError("Input JSON must be a list of chunk records.")

    chunks: List[Dict[str, Any]] = []
    for raw in payload:
        if not isinstance(raw, dict):
            continue
        normalized = _normalize_chunk_record(raw)
        if normalized is not None:
            chunks.append(normalized)

    if limit is not None and limit >= 0:
        chunks = chunks[:limit]

    if not chunks:
        raise ValueError("No valid chunks found after normalization.")

    return chunks


class BM25Indexer:
    def __init__(self, export_path: Path):
        self.export_path = export_path

    def build_and_save(self, chunks: Sequence[Dict[str, Any]]) -> None:
        try:
            from rank_bm25 import BM25Okapi
        except ImportError as exc:  # pragma: no cover
            raise RuntimeError(
                "Missing dependency 'rank_bm25'. Install it with: pip install rank-bm25"
            ) from exc

        ensure_parent(self.export_path)

        corpus = [chunk["content"] for chunk in chunks]
        metadata = [chunk["metadata"] for chunk in chunks]

        safe_console_print("\n[BM25] Tokenizing corpus...")
        # tokenized_corpus = [simple_tokenize(doc) for doc in corpus]
        tokenized_corpus = [
            ViTokenizer.tokenize(doc.lower()).split() for doc in corpus
        ]

        safe_console_print("[BM25] Building model...")
        bm25_model = BM25Okapi(tokenized_corpus)

        with self.export_path.open("wb") as f:
            pickle.dump(
                {
                    "bm25_model": bm25_model,
                    "corpus": corpus,
                    "metadata": metadata,
                },
                f,
            )

        safe_console_print(f"[BM25] Saved index: {self.export_path.as_posix()}")


class VectorDBIndexer:
    def __init__(
        self,
        collection_name: str,
        qdrant_path: Path,
        embedding_model_name: str,
        recreate_collection: bool,
    ):
        try:
            from sentence_transformers import SentenceTransformer
            import torch
            from qdrant_client import QdrantClient
            from qdrant_client.http import models

            device = "cuda" if torch.cuda.is_available() else "cpu"
        except ImportError as exc:  # pragma: no cover
            raise RuntimeError(
                "Missing vector dependencies. Install with: pip install sentence-transformers qdrant-client"
            ) from exc

        self.models = models
        self.collection_name = collection_name
        self.qdrant_path = qdrant_path
        self.qdrant_path.mkdir(parents=True, exist_ok=True)

        safe_console_print(f"\n[Vector] Loading embedding model: {embedding_model_name}")
        self.embedding_model = SentenceTransformer(embedding_model_name)

        safe_console_print(f"[Vector] Opening Qdrant at: {self.qdrant_path.as_posix()}")
        self.qdrant_client = QdrantClient(path=str(self.qdrant_path))

        self._prepare_collection(recreate_collection=recreate_collection)

    def _prepare_collection(self, recreate_collection: bool) -> None:
        vector_size = self.embedding_model.get_sentence_embedding_dimension()

        try:
            exists = self.qdrant_client.collection_exists(self.collection_name)
        except Exception:
            exists = False

        if recreate_collection and exists:
            self.qdrant_client.delete_collection(collection_name=self.collection_name)
            exists = False

        if not exists:
            self.qdrant_client.create_collection(
                collection_name=self.collection_name,
                vectors_config=self.models.VectorParams(
                    size=vector_size,
                    distance=self.models.Distance.COSINE,
                ),
            )
            action = "Recreated" if recreate_collection else "Created"
            safe_console_print(
                f"[Vector] {action} collection '{self.collection_name}' (dim={vector_size})"
            )
        else:
            safe_console_print(f"[Vector] Using existing collection '{self.collection_name}'")

    def process_and_upload(self, chunks: Sequence[Dict[str, Any]], batch_size: int = 32) -> None:
        safe_console_print(f"[Vector] Encoding and uploading {len(chunks)} chunks...")

        for start in range(0, len(chunks), batch_size):
            batch = chunks[start : start + batch_size]

            batch_texts = [item["content"] for item in batch]
            batch_ids = list(range(start, start + len(batch)))
            batch_payloads = []
            for item in batch:
                payload = dict(item["metadata"])
                payload["content"] = item["content"]
                batch_payloads.append(payload)

            embeddings = self.embedding_model.encode(
                batch_texts,
                batch_size=batch_size,
                show_progress_bar=False,
                normalize_embeddings=True,
            )

            self.qdrant_client.upsert(
                collection_name=self.collection_name,
                points=self.models.Batch(
                    ids=batch_ids,
                    vectors=embeddings.tolist(),
                    payloads=batch_payloads,
                ),
            )

            end = min(start + batch_size, len(chunks))
            safe_console_print(f"[Vector] Uploaded {end}/{len(chunks)}")

        safe_console_print("[Vector] Upload complete.")


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Build BM25 and Qdrant indexes for legal chunks.")
    parser.add_argument(
        "--input_file",
        type=str,
        default="data/metadata/processed_data.json",
        help="Chunk JSON path (default: data/metadata/processed_data.json).",
    )
    parser.add_argument(
        "--bm25_out",
        type=str,
        default="data/indexes/bm25_index.pkl",
        help="BM25 output path (default: data/indexes/bm25_index.pkl).",
    )
    parser.add_argument(
        "--qdrant_path",
        type=str,
        default="data/indexes/qdrant_db",
        help="Qdrant local storage directory (default: data/indexes/qdrant_db).",
    )
    parser.add_argument(
        "--collection_name",
        type=str,
        default="legal_documents",
        help="Qdrant collection name (default: legal_documents).",
    )
    parser.add_argument(
        "--embedding_model",
        type=str,
        default="huyydangg/DEk21_hcmute_embedding",
        help="SentenceTransformer model name (default: huyydangg/DEk21_hcmute_embedding).",
    )
    parser.add_argument(
        "--batch_size",
        type=int,
        default=32,
        help="Batch size for embedding and upload (default: 32).",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Optional chunk limit for quick tests.",
    )
    parser.add_argument(
        "--skip_bm25",
        action="store_true",
        help="Skip BM25 indexing.",
    )
    parser.add_argument(
        "--skip_vector",
        action="store_true",
        help="Skip vector indexing.",
    )
    parser.add_argument(
        "--recreate_collection",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Recreate Qdrant collection before upload (default: true).",
    )
    return parser


def main() -> None:
    parser = build_arg_parser()
    args = parser.parse_args()

    if args.skip_bm25 and args.skip_vector:
        safe_console_print("Both --skip_bm25 and --skip_vector are set. Nothing to do.")
        return

    chunks = load_chunks(Path(args.input_file), limit=args.limit)
    safe_console_print(f"Loaded {len(chunks)} chunk(s) from {args.input_file}")

    if not args.skip_bm25:
        bm25_indexer = BM25Indexer(export_path=Path(args.bm25_out))
        bm25_indexer.build_and_save(chunks)

    if not args.skip_vector:
        vector_indexer = VectorDBIndexer(
            collection_name=args.collection_name,
            qdrant_path=Path(args.qdrant_path),
            embedding_model_name=args.embedding_model,
            recreate_collection=args.recreate_collection,
        )
        vector_indexer.process_and_upload(chunks, batch_size=args.batch_size)


if __name__ == "__main__":
    main()
